
(function(){
 const RUNTIME_KEYS=['paramio_oem_project_runtime_core_v207','paramio_oem_project_runtime_core_v206','paramio_oem_project_state_latest_core_v207','paramio_oem_project_state_latest_core_v206','paramio_oem_project_runtime_core_v204','paramio_oem_project_state_latest_core_v204','paramio_oem_project_runtime_v167','paramio_oem_project_state_latest_v167'];
 window.PARAMIO_VERSION='V207 rule fixes';
 window.esc=function(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));};
 window.num=function(v){let n=parseFloat(String(v??'').replace(',','.').replace(/[^\d.-]/g,''));return Number.isFinite(n)?n:NaN;};
 window.fmt=function(v){return v==null?'':String(v).trim();};
 window.norm=function(v){return String(v??'').toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();};
 window.normalizeProject=function(p){p=p||{};if(!p.characteristics&&p.stableState&&p.stableState.characteristics)p.characteristics=p.stableState.characteristics;if(!p.meta&&p.stableState&&p.stableState.meta)p.meta=p.stableState.meta;p.meta=p.meta||{};p.characteristics=Array.isArray(p.characteristics)?p.characteristics:[];p.manualResults=p.manualResults||{};p.pcdmisBlocks=p.pcdmisBlocks||{};p.characteristics.forEach(c=>{if(!c.results)c.results={};if(typeof c.kcs==='undefined')c.kcs=false;});return p;};
 window.saveProject=function(p){p=normalizeProject(p);p.savedAt=new Date().toISOString();p.parserVersion='CORE_V207';p.savedBy='V207 rule fixes';const s=JSON.stringify(p);for(const k of RUNTIME_KEYS){try{localStorage.setItem(k,s);}catch(e){}try{sessionStorage.setItem(k,s);}catch(e){}}return true;};
 window.loadProject=function(){for(const store of [localStorage,sessionStorage]){for(const k of RUNTIME_KEYS){try{const raw=store.getItem(k);if(!raw)continue;const p=normalizeProject(JSON.parse(raw));if(p&&p.characteristics&&p.characteristics.length)return p;}catch(e){}}}let best=null,score=-1;for(const store of [localStorage,sessionStorage]){for(let i=0;i<store.length;i++){const k=store.key(i);if(!/paramio|oem/i.test(k))continue;try{const p=normalizeProject(JSON.parse(store.getItem(k)));const s=(p.characteristics?.length||0)+(p.linkedResults||0);if(p.characteristics?.length&&s>score){best=p;score=s;}}catch(e){}}}return best;};
 window.clearProject=function(){for(const store of [localStorage,sessionStorage]){Object.keys(store).forEach(k=>{if(/paramio|oem/i.test(k))store.removeItem(k);});}};
 window.renderShell=function(active){return `<aside class="side"><div class="logo"><img src="assets/logo_paramio.png" onerror="this.src='assets/paramio-logo.png';this.onerror=null" alt="Paramio"></div><nav class="nav"><a class="${active==='home'?'active':''}" href="index.html">⌂ Inicio / Cargar</a><a class="${active==='diag'?'active':''}" href="diagnostico.html">◆ Diagnóstico</a><a class="${active==='isir'?'active':''}" href="isir.html">▦ ISIR</a><a class="${active==='dimensional'?'active':''}" href="dimensional.html">▤ Dimensional</a><a class="${active==='kcs'?'active':''}" href="kcs.html">◆ Seleccionar KCS</a><a class="${active==='plan'?'active':''}" href="control-plan.html">▣ Plan de control</a><a class="${active==='flow'?'active':''}" href="flowchart.html">↔ Flowchart</a></nav><div class="sideFoot"><b>V207 rule fixes</b><br>Parser RAW + strategies independientes.</div></aside>`;};
 window.noDataHtml=function(){return `<div class="card"><h2>No hay datos cargados</h2><p>Primero ve a Inicio, carga Excel Inspection + PC-DMIS y pulsa <b>Procesar documentación</b>.</p><div class="actions"><a class="btn green" href="index.html">Ir a cargar Excel</a></div></div>`;};
 window.metaHtml=function(p){const m=(p||{}).meta||{};return `<div class="metaBox">Cliente: ${esc(m.client||'')}<br>Referencia: ${esc(m.reference||'')}<br>Pieza: ${esc(m.partName||'')}<br>Rev.: ${esc(m.revision||'')}<br>Fecha: ${esc(m.date||'')}</div>`;};
})();
