document.write(renderShell('plan'))

const PLAN_VERSION='V225_OEM_CONTROL_PLAN';
const OPS_KEY='paramio_control_plan_ops_v225';
const OV_KEY='paramio_control_plan_overrides_v225';
const LIB_KEY='paramio_control_plan_library_v225';
const ROUTE_KEY='paramio_control_plan_route_v225';
let project=applyKcsSelectionToProject(loadProject()||{});
const root=document.getElementById('root');
function cpNorm(v){return String(v??'').toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();}
function cpNum(v){const n=parseFloat(String(v??'').replace(',','.').replace(/[^0-9.\-]/g,''));return Number.isFinite(n)?n:NaN;}
function sig(){return getProjectSignature(project||{});}
function storeKey(base){return base+'__'+sig();}
function loadJson(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch(e){return fallback;}}
function saveJson(key,val){try{localStorage.setItem(key,JSON.stringify(val));}catch(e){}}
function cpType(c){return normalizeFeatureType(c?.featureType||c?.rawValue||c?.decodedValue||c?.value||'');}
function cpClean(c){return cleanFeatureText?cleanFeatureText(c?.value||c?.rawValue||'',c?.number):cleanChar(c?.value||'');}
function cpSpec(c){const lo=String(c.lower??c.li??'').trim();const up=String(c.upper??c.ls??'').trim();const unit=String(c.units??c.unit??'').trim();if(lo||up)return `LI ${esc(lo)} / LS ${esc(up)} ${esc(unit)}`.trim();return esc(c.value||c.rawValue||'');}
function cpIsKcs(c){const map=loadKcsSelection(project);return !!map[String(c.number)]||!!c.kcs;}
function phase(){return loadJson(storeKey(ROUTE_KEY),{phase:'Producción',preparedBy:'Calidad',approvedBy:'',docNo:'PC-'+((project.meta||{}).reference||'REFERENCIA'),rev:'01'});}
function savePhaseField(field,value){const r=phase();r[field]=value;saveJson(storeKey(ROUTE_KEY),r);}
const BASE_ROWS=[
 {band:true,op:'010',title:'RECEPCIÓN DE MATERIA PRIMA'},
 {id:'base-010-1',op:'010',process:'Recepción MP',machine:'Almacén / recepción',controlClass:'Documental',characteristic:'Conformidad con pedido, albarán y documentación de lote',specification:'Referencia, cantidad, lote y certificado correctos según pedido/cliente',method:'Revisión documental',equipment:'Pedido / albarán / certificado',sample:'100%',frequency:'Cada lote recibido',owner:'Logística / Calidad',reaction:'Retener material; identificar no conforme; comunicar a compras/proveedor'},
 {id:'base-010-2',op:'010',process:'Recepción MP',machine:'Almacén / recepción',controlClass:'Producto',characteristic:'Estado visual del material y embalaje',specification:'Sin golpes, daños, oxidación, contaminación ni embalaje deteriorado',method:'Inspección visual',equipment:'Visual / instrucción recepción',sample:'1 lote',frequency:'Cada recepción',owner:'Logística',reaction:'Bloquear material; abrir incidencia; avisar Calidad'},
 {band:true,op:'015',title:'PREPARACIÓN DE MÁQUINA, HERRAMIENTAS Y UTILLAJES'},
 {id:'base-015-1',op:'015',process:'Preparación',machine:'Máquina / utillaje',controlClass:'Proceso',characteristic:'Utillaje, amarre y posicionadores correctos',specification:'Conforme a hoja de proceso, presión de amarre, apoyos limpios y localización correcta',method:'Checklist de arranque',equipment:'Checklist / manómetro / hoja técnica',sample:'1',frequency:'Inicio de lote / cambio referencia',owner:'Producción',reaction:'Parar preparación; corregir amarre/utillaje; validar primera pieza'},
 {id:'base-015-2',op:'015',process:'Preparación',machine:'CNC / programa',controlClass:'Proceso',characteristic:'Programa CNC, herramientas y correctores cargados',specification:'Programa y tabla de herramientas de revisión vigente',method:'Verificación de programa',equipment:'Hoja proceso / lista herramientas / presetting',sample:'1',frequency:'Inicio lote / cambio herramienta',owner:'Responsable línea',reaction:'No iniciar producción; corregir programa/corrector; registrar incidencia'},
 {id:'base-015-3',op:'015',process:'Preparación',machine:'Máquina / refrigerante',controlClass:'Proceso',characteristic:'Condición del refrigerante / taladrina',specification:'Concentración dentro del rango definido por proceso/mantenimiento',method:'Medición concentración',equipment:'Refractómetro',sample:'1',frequency:'Según plan mantenimiento / inicio turno si aplica',owner:'Producción',reaction:'Ajustar concentración; avisar mantenimiento si fuera de rango'},
 {band:true,op:'020',title:'MECANIZADO / PROCESO PRINCIPAL'},
 {band:true,op:'030',title:'REBARBADO, LIMPIEZA Y SOPLADO'},
 {id:'base-030-1',op:'030',process:'Rebarbado',machine:'Banco rebarbado',controlClass:'Proceso',characteristic:'Ausencia de rebabas y aristas peligrosas',specification:'Sin rebabas cortantes ni restos de mecanizado en zonas funcionales',method:'Visual / táctil',equipment:'Visual / útil manual',sample:'100%',frequency:'Cada pieza',owner:'Producción',reaction:'Repetir rebarbado; segregar pieza si no recuperable'},
 {id:'base-030-2',op:'030',process:'Limpieza / soplado',machine:'Aire comprimido / lavado',controlClass:'Proceso',characteristic:'Ausencia de viruta, suciedad y humedad',specification:'Pieza limpia; conductos y zonas críticas libres de viruta',method:'Visual / soplado',equipment:'Aire comprimido / instrucción limpieza',sample:'100%',frequency:'Cada pieza / cada lote según proceso',owner:'Producción',reaction:'Repetir limpieza; revisar proceso si hay recurrencia'},
 {band:true,op:'050',title:'EMBALAJE, IDENTIFICACIÓN Y EXPEDICIÓN'},
 {id:'base-050-1',op:'050',process:'Embalaje',machine:'Zona embalaje',controlClass:'Proceso',characteristic:'Embalaje y protección conforme',specification:'Embalaje según especificación cliente; pieza protegida contra daños/transporte',method:'Inspección visual',equipment:'Instrucción embalaje / contenedor cliente',sample:'100%',frequency:'Cada envío',owner:'Logística',reaction:'Retener envío; corregir embalaje; avisar responsable'},
 {id:'base-050-2',op:'050',process:'Expedición',machine:'Almacén / sistema',controlClass:'Documental',characteristic:'Identificación, etiqueta y documentación de expedición',specification:'Referencia, revisión, lote, cantidad, albarán/RPS correctos',method:'Verificación documental',equipment:'Etiqueta / sistema / albarán',sample:'100%',frequency:'Cada envío',owner:'Logística',reaction:'Retener envío; corregir documentación/etiqueta antes de expedir'},
 {band:true,op:'060',title:'AUDITORÍAS Y VERIFICACIÓN DOCUMENTAL'},
 {id:'base-060-1',op:'060',process:'Auditoría proceso',machine:'Línea / proceso',controlClass:'Auditoría',characteristic:'Auditoría de proceso y cumplimiento de pauta',specification:'Proceso conforme a hoja de proceso, plan de control e instrucciones vigentes',method:'Auditoría proceso',equipment:'Checklist auditoría / registros',sample:'1',frequency:'Según plan auditorías',owner:'Calidad',reaction:'Abrir acción correctiva; contener lote/proceso si hay riesgo'},
 {id:'base-060-2',op:'060',process:'Auditoría producto',machine:'Producto terminado',controlClass:'Auditoría',characteristic:'Auditoría de producto terminado',specification:'Conformidad con plano, requisitos cliente y documentación de calidad',method:'Auditoría producto',equipment:'Plano / ISIR / pauta / informe dimensional',sample:'1',frequency:'Según plan auditorías / requisito cliente',owner:'Calidad',reaction:'Contención de lote; análisis causa; acción correctiva'}
];
const TEMPLATES={
  '040 LAVADO FINAL':{op:'040',process:'Lavado final',machine:'Lavadora / soplado final',controlClass:'Proceso',characteristic:'Limpieza final de pieza',specification:'Pieza limpia, seca y sin contaminación en zonas críticas',method:'Proceso lavado + inspección visual',equipment:'Lavadora / aire comprimido / instrucción limpieza',sample:'1 lote',frequency:'Cada lote',owner:'Producción',reaction:'Repetir lavado; retener lote si persiste contaminación'},
  '045 MARCADO':{op:'045',process:'Marcado',machine:'Marcadora / láser / etiqueta',controlClass:'Proceso',characteristic:'Marcado e identificación de pieza',specification:'Marcado legible, correcto y conforme a especificación cliente',method:'Inspección visual',equipment:'Patrón marcado / plano cliente',sample:'100%',frequency:'Cada pieza / cada lote según requisito',owner:'Producción',reaction:'Retener pieza/lote; corregir marcado; avisar Calidad'},
  '070 CONTROL FINAL':{op:'070',process:'Control final',machine:'Zona calidad',controlClass:'Producto',characteristic:'Verificación final documental y visual',specification:'Pieza conforme antes de expedición',method:'Revisión final',equipment:'Pauta control / ISIR / registros',sample:'1',frequency:'Cada lote',owner:'Calidad',reaction:'Retener lote; abrir no conformidad; definir disposición'}
};
function defaultRule(c){
 const t=cpType(c);const kcs=cpIsKcs(c);let r={controlClass:'Producto',method:'Medición dimensional',equipment:'Pie de rey / micrómetro / calibre / CMM según acceso',sample:'2',frequency:'Inicio de serie / 1 turno',owner:'Producción / Calidad',reaction:'Ajustar proceso; verificar pieza siguiente; segregar piezas NOK'};
 if(['POSITION','PROFILE','FLATNESS','ANGULARITY','PARALLELISM','PERPENDICULARITY','CIRCULARITY','CYLINDRICITY','RUNOUT','TOTAL_RUNOUT'].includes(t))r={controlClass:'Producto',method:'Control geométrico',equipment:'3D / Máquina tridimensional CMM',sample:'1',frequency:'Inicio de serie / 1 turno / cambio ajuste',owner:'Calidad / Metrología',reaction:'Retener pieza; revisar amarre, programa y proceso; repetir medición; contener lote'};
 if(t==='DIAMETER')r={controlClass:'Producto',method:'Medición dimensional',equipment:'Alexómetro / micrómetro / CMM según acceso',sample:'2',frequency:'Inicio de serie / 1 turno / cambio herramienta',owner:'Producción / Calidad',reaction:'Ajustar corrector; revisar herramienta; controlar pieza siguiente'};
 if(t==='THREAD')r={controlClass:'Producto',method:'Control rosca',equipment:'Tampón rosca P/NP',sample:'1',frequency:'Inicio serie / cambio herramienta / 1 turno',owner:'Producción / Calidad',reaction:'Rechazar pieza; revisar macho/herramienta; contener lote'};
 if(t==='DEPTH')r={controlClass:'Producto',method:'Medición dimensional',equipment:'Sonda profundidad / CMM / pie de rey según acceso',sample:'2',frequency:'Inicio serie / 1 turno',owner:'Producción / Calidad',reaction:'Ajustar corrector; verificar pieza siguiente; contener lote'};
 if(t==='RADIUS')r={controlClass:'Producto',method:'Control radio',equipment:'Plantilla radios / proyector / presetting / CMM si aplica',sample:'2',frequency:'Inicio serie / cambio herramienta',owner:'Producción / Calidad',reaction:'Ajustar herramienta; verificar pieza siguiente; segregar NOK'};
 if(kcs){r.sample='3';r.frequency='KCS: inicio + cada 50 piezas / cambios y ajustes';r.reaction='KCS: contención inmediata desde última pieza OK; parar producción si no controlado; avisar Calidad y Producción';}
 return r;
}
function loadOverrides(){return loadJson(storeKey(OV_KEY),{});}function saveOverrides(o){saveJson(storeKey(OV_KEY),o);}function rowKey(row){return row.key||row.id||('row_'+row.op+'_'+row.characteristic);}function getVal(row,field){const o=loadOverrides();const k=rowKey(row);return o[k]&&Object.prototype.hasOwnProperty.call(o[k],field)?o[k][field]:(row[field]??'');}function setVal(k,field,val){const o=loadOverrides();o[k]=o[k]||{};o[k][field]=val;saveOverrides(o);}function edit(row,field,cls=''){const k=rowKey(row),v=getVal(row,field);const long=['method','equipment','frequency','owner','reaction','specification','characteristic'].includes(field);if(long)return `<textarea class="pcEdit pcArea ${cls}" onchange="setVal('${esc(k)}','${field}',this.value)" oninput="this.style.height='auto';this.style.height=this.scrollHeight+'px'">${esc(v)}</textarea>`;return `<input class="pcEdit ${cls}" value="${esc(v)}" onchange="setVal('${esc(k)}','${field}',this.value)">`;}
function charRows(){const chars=(project.characteristics||[]);return chars.map(c=>{const rule=defaultRule(c);return {key:'char_'+c.number,source:'inspection',op:'020',process:'Mecanizado',machine:'Máquina asignada / medio productivo',globo:String(c.number),kcs:cpIsKcs(c),controlClass:rule.controlClass,featureType:cpType(c),characteristic:cpClean(c),specification:cpSpec(c),method:rule.method,equipment:rule.equipment,sample:rule.sample,frequency:rule.frequency,owner:rule.owner,reaction:rule.reaction};});}
function loadLibrary(){return loadJson(storeKey(LIB_KEY),[]);}function saveLibrary(a){saveJson(storeKey(LIB_KEY),a||[]);}function addTemplate(name){const t=Object.assign({},TEMPLATES[name]||{});if(!t.op)return;const lib=loadLibrary();t.id='lib_'+Date.now();lib.push(t);saveLibrary(lib);render();}function addCustomOp(){const lib=loadLibrary();lib.push({id:'lib_'+Date.now(),op:document.getElementById('newOp').value||'040',process:document.getElementById('newProcess').value||'Operación añadida',machine:document.getElementById('newMachine').value||'',controlClass:document.getElementById('newClass').value||'Proceso',characteristic:document.getElementById('newChar').value||'',specification:document.getElementById('newSpec').value||'',method:document.getElementById('newMethod').value||'',equipment:document.getElementById('newEquip').value||'',sample:document.getElementById('newSample').value||'',frequency:document.getElementById('newFreq').value||'',owner:document.getElementById('newOwner').value||'',reaction:document.getElementById('newReact').value||''});saveLibrary(lib);render();}function deleteLib(id){if(!confirm('Eliminar operación de biblioteca?'))return;saveLibrary(loadLibrary().filter(x=>x.id!==id));render();}
function allRows(){const lib=loadLibrary().map(x=>Object.assign({source:'library'},x));const rows=[];BASE_ROWS.forEach(r=>{rows.push(r);if(r.band&&r.op==='020'){charRows().forEach(c=>rows.push(c));lib.filter(x=>String(x.op||'').padStart(3,'0')>='020'&&String(x.op||'').padStart(3,'0')<'030').forEach(x=>rows.push(x));}});lib.filter(x=>{const op=String(x.op||'').padStart(3,'0');return op<'020'||op>='030';}).forEach(x=>rows.push(x));return rows.sort((a,b)=>{if(a.band||b.band)return 0;return String(getVal(a,'op')||a.op).localeCompare(String(getVal(b,'op')||b.op),undefined,{numeric:true});});}
function badge(row){if(row.kcs)return '<span class="pcBadge kcs">KCS</span>';const c=cpNorm(row.controlClass);if(c.includes('DOCUMENT'))return '<span class="pcBadge doc">Documental</span>';if(c.includes('AUDIT'))return '<span class="pcBadge audit">Auditoría</span>';if(c.includes('PROCES'))return '<span class="pcBadge proc">Proceso</span>';return '<span class="pcBadge prod">Producto</span>';}
function filteredRows(){const q=cpNorm(document.getElementById('filterText')?.value||'');const mode=document.getElementById('filterMode')?.value||'ALL';let rows=allRows();if(mode==='KCS')rows=rows.filter(r=>r.band||r.kcs);if(mode==='INSPECTION')rows=rows.filter(r=>r.band||r.source==='inspection');if(mode==='BASE')rows=rows.filter(r=>r.band||(!r.source||r.source==='base'));if(q)rows=rows.filter(r=>r.band||cpNorm(Object.values(r).join(' ')).includes(q));return rows;}
function renderTable(rows){let currentBand='';let html='';rows.forEach(r=>{if(r.band){currentBand=r.op;html+=`<tr class="opBand"><td colspan="16">OP ${esc(r.op)} · ${esc(r.title)}</td></tr>`;return;}const src=r.source==='inspection'?'inspectionRow':(r.source==='library'?'libraryRow':'baseRow');html+=`<tr class="${src} ${r.kcs?'kcsRow':''}">
<td>${edit(r,'op','op')}</td><td>${edit(r,'process')}</td><td>${edit(r,'machine')}</td><td class="pcCenter">${esc(r.globo||'')}</td><td>${badge(r)}</td><td class="pcCenter"><b>${esc(r.featureType||'')}</b></td><td>${edit(r,'characteristic')}</td><td>${edit(r,'specification')}</td><td>${edit(r,'method')}</td><td>${edit(r,'equipment')}</td><td>${edit(r,'sample','sample')}</td><td>${edit(r,'frequency')}</td><td>${edit(r,'owner')}</td><td>${edit(r,'reaction')}</td><td class="pcMuted">${r.source==='inspection'?'Inspection':r.source==='library'?'Biblioteca':'Fija'}</td><td class="pcActionsCell">${r.source==='library'?`<button class="pcMini red" onclick="deleteLib('${esc(r.id)}')">Eliminar</button>`:''}</td></tr>`;});return html;}
function exportCsv(){const rows=allRows().filter(r=>!r.band);const headers=['OP','Proceso','Máquina/útiles','Globo','Clase','Tipo cota','Característica/control','Especificación','Método','Equipo','Muestra','Frecuencia','Responsable','Reacción','Origen'];const lines=[headers.join(';')];rows.forEach(r=>{lines.push([getVal(r,'op'),getVal(r,'process'),getVal(r,'machine'),r.globo||'',r.kcs?'KCS':getVal(r,'controlClass'),r.featureType||'',getVal(r,'characteristic'),getVal(r,'specification'),getVal(r,'method'),getVal(r,'equipment'),getVal(r,'sample'),getVal(r,'frequency'),getVal(r,'owner'),getVal(r,'reaction'),r.source||'base'].map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';'));});const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='plan_control_'+((project.meta||{}).reference||'referencia')+'_V225.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function exportLibrary(){const blob=new Blob([JSON.stringify(loadLibrary(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='biblioteca_operaciones_plan_control.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}function importLibrary(ev){const f=ev.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const arr=JSON.parse(r.result);if(!Array.isArray(arr))throw new Error('Formato no válido');saveLibrary(arr);render();}catch(e){alert('No se pudo importar: '+e.message);}};r.readAsText(f,'utf-8');}
function clearEdits(){if(confirm('Borrar cambios manuales del plan para esta referencia?')){localStorage.removeItem(storeKey(OV_KEY));render();}}
function render(){project=applyKcsSelectionToProject(loadProject()||{});if(!project||!project.characteristics||!project.characteristics.length){root.innerHTML=noDataHtml();return;}const m=project.meta||{},ph=phase();const kcsCount=charRows().filter(r=>r.kcs).length;root.innerHTML=`
<section class="cpHeader"><div class="cpHeaderTop"><div class="cpLogoBox"><img src="assets/logo_paramio.png" onerror="this.src='assets/paramio-logo.png';this.onerror=null"></div><div class="cpTitleBox"><h2>PLAN DE CONTROL</h2><p>Control Plan · ${esc(ph.phase||'Producción')}</p></div><div class="cpDocBox"><div>Documento</div><div>${esc(ph.docNo||'')}</div><div>Revisión</div><div>${esc(ph.rev||'01')}</div><div>Versión app</div><div>${PLAN_VERSION}</div></div></div><div class="cpMeta"><div class="lab">Cliente</div><div class="val">${esc(m.client||'')}</div><div class="lab">Referencia</div><div class="val">${esc(m.reference||'')}</div><div class="lab">Rev. pieza</div><div class="val">${esc(m.revision||'')}</div><div class="lab">Denominación</div><div class="val">${esc(m.partName||'')}</div><div class="lab">Fecha</div><div class="val">${esc(m.date||new Date().toISOString().slice(0,10))}</div><div class="lab">Fase</div><div class="val">${esc(ph.phase||'Producción')}</div><div class="lab">Preparado por</div><div class="val">${esc(ph.preparedBy||'Calidad')}</div><div class="lab">Aprobado por</div><div class="val">${esc(ph.approvedBy||'')}</div><div class="lab">KCS</div><div class="val">${kcsCount} características</div></div></section>
<section class="cpPanel noPrint"><h3>Configuración documental</h3><div class="cpGrid wide"><div><label>Fase</label><select class="cpSelect phaseSelect" onchange="savePhaseField('phase',this.value);render()"><option ${ph.phase==='Prototipo'?'selected':''}>Prototipo</option><option ${ph.phase==='Pre-serie'?'selected':''}>Pre-serie</option><option ${ph.phase==='Producción'?'selected':''}>Producción</option></select></div><div><label>Nº documento</label><input class="cpInput" value="${esc(ph.docNo||'')}" onchange="savePhaseField('docNo',this.value);render()"></div><div><label>Preparado por</label><input class="cpInput" value="${esc(ph.preparedBy||'Calidad')}" onchange="savePhaseField('preparedBy',this.value);render()"></div><div><label>Aprobado por</label><input class="cpInput" value="${esc(ph.approvedBy||'')}" onchange="savePhaseField('approvedBy',this.value);render()"></div></div></section>
<section class="cpToolbar noPrint"><input id="filterText" class="cpInput search" placeholder="Filtrar operación, característica, método, equipo..." oninput="renderTableOnly()"><select id="filterMode" class="cpSelect" onchange="renderTableOnly()"><option value="ALL">Todo</option><option value="KCS">Solo KCS</option><option value="INSPECTION">Solo Inspection</option><option value="BASE">Solo operaciones base</option></select><button class="btn light" onclick="exportCsv()">Exportar CSV</button><button class="btn light" onclick="exportLibrary()">Exportar biblioteca</button><label class="btn light">Importar biblioteca <input type="file" accept=".json" style="display:none" onchange="importLibrary(event)"></label><button class="btn light" onclick="clearEdits()">Borrar ediciones</button><button class="btn" onclick="window.print()">Guardar PDF / Imprimir</button></section>
<section class="cpPanel noPrint"><h3>Biblioteca de operaciones</h3><p class="cpHint">Añade operaciones completas de la pieza. Las cotas de Inspection se asignan por defecto a OP 020, pero cada fila puede editarse para moverla a otra operación.</p><div class="actions"><button class="btn light" onclick="addTemplate('040 LAVADO FINAL')">+ Lavado final</button><button class="btn light" onclick="addTemplate('045 MARCADO')">+ Marcado</button><button class="btn light" onclick="addTemplate('070 CONTROL FINAL')">+ Control final</button></div><div class="cpGrid" style="margin-top:10px"><div><label>OP</label><input id="newOp" class="cpInput" value="040"></div><div><label>Proceso</label><input id="newProcess" class="cpInput" placeholder="Operación"></div><div><label>Máquina / útiles</label><input id="newMachine" class="cpInput" placeholder="Medio productivo"></div><div><label>Clase</label><select id="newClass" class="cpSelect"><option>Proceso</option><option>Producto</option><option>Documental</option><option>Auditoría</option></select></div><div><label>Característica</label><input id="newChar" class="cpInput" placeholder="Qué se controla"></div><div><label>Especificación</label><input id="newSpec" class="cpInput" placeholder="Criterio"></div><div><label>Método</label><input id="newMethod" class="cpInput" placeholder="Cómo se controla"></div><div><label>Equipo</label><input id="newEquip" class="cpInput" placeholder="Medio de control"></div><div><label>Muestra</label><input id="newSample" class="cpInput" value="100%"></div><div><label>Frecuencia</label><input id="newFreq" class="cpInput" placeholder="Frecuencia"></div><div><label>Responsable</label><input id="newOwner" class="cpInput" value="Producción"></div><div><label>Reacción</label><input id="newReact" class="cpInput" placeholder="Acción ante NOK"></div></div><div class="actions"><button class="btn green" onclick="addCustomOp()">Añadir operación</button></div></section>
<section class="cpTableWrap"><table class="cpTable"><thead><tr><th>Nº OP</th><th>Descripción operación</th><th>Máquina / útiles</th><th>Globo</th><th>Clasificación</th><th>Tipo cota</th><th>Característica producto / proceso</th><th>Especificación / tolerancia</th><th>Método de evaluación</th><th>Equipo / medio control</th><th>Muestra</th><th>Frecuencia</th><th>Responsable</th><th>Plan de reacción</th><th>Origen</th><th class="noPrint">Acción</th></tr></thead><tbody id="planBody">${renderTable(filteredRows())}</tbody></table></section><div class="cpFooterNote"><span>Documento generado desde Paramio Quality Documentation · ${PLAN_VERSION}</span><span>Las mediciones/resultados se gestionan en ISIR y Dimensional; el Plan de Control mantiene método, frecuencia, responsabilidad y reacción.</span></div>`;}
function renderTableOnly(){const body=document.getElementById('planBody');if(body)body.innerHTML=renderTable(filteredRows());}
render();
